catalog: HDLM_WEU_2
version: null
download_method: OLP_CLI

target:
  type: coordinate
  coordinate: { lat: 52.24657209517959, lng: 10.50807094760168 }

layers:
#  - adas-attributes
#  - external-reference-attributes
#  - localization-sign
#  - localization-pole
#  - lane-topology
#  - lane-geometry-polyline
#  - localization-barrier
#  - lane-road-references
#  - localization-overhead-structure-face
#  - lane-attributes
#  - routing-lane-attributes
#  - routing-attributes
#  - speed-attributes
#  - topology-geometry
